---
# Webmin handlers

- name: Restart webmin
  ansible.builtin.systemd:
    name: webmin
    state: restarted

- name: Reload nginx (webmin)
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Save iptables rules
  shell: iptables-save > /etc/sysconfig/iptables
  when: ansible_os_family == 'RedHat'
  changed_when: false
